package org.tenio.interstellar.dao.mybatis;

import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GenericMapper<T, E, K> {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     */
    int countByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     */
    int deleteByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     */
    int deleteByPrimaryKey(K id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     */
    List<T> selectByExample(E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     */
    T selectByPrimaryKey(K id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     */
    int updateByExampleSelective(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     */
    int updateByExample(@Param("record") T record, @Param("example") E example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     */
    int updateByPrimaryKey(T record);
}
