package org.tenio.interstellar.example.panda.model;

public class UserBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.gid
     *
     * @mbggenerated
     */
    private String gid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.id_card
     *
     * @mbggenerated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.portrait_url
     *
     * @mbggenerated
     */
    private String portraitUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.login_pwd_hash
     *
     * @mbggenerated
     */
    private String loginPwdHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.is_migrated
     *
     * @mbggenerated
     */
    private Boolean isMigrated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.hash_mobile
     *
     * @mbggenerated
     */
    private String hashMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.hash_id_card
     *
     * @mbggenerated
     */
    private String hashIdCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_base.hash_name
     *
     * @mbggenerated
     */
    private String hashName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.id
     *
     * @return the value of user_base.id
     * @mbggenerated
     */
    private String bizType;

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.id
     *
     * @param id the value for user_base.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.gid
     *
     * @return the value of user_base.gid
     * @mbggenerated
     */
    public String getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.gid
     *
     * @param gid the value for user_base.gid
     * @mbggenerated
     */
    public void setGid(String gid) {
        this.gid = gid == null ? null : gid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.create_time
     *
     * @return the value of user_base.create_time
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.create_time
     *
     * @param createTime the value for user_base.create_time
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.update_time
     *
     * @return the value of user_base.update_time
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.update_time
     *
     * @param updateTime the value for user_base.update_time
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.nickname
     *
     * @return the value of user_base.nickname
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.nickname
     *
     * @param nickname the value for user_base.nickname
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.mobile
     *
     * @return the value of user_base.mobile
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.mobile
     *
     * @param mobile the value for user_base.mobile
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.name
     *
     * @return the value of user_base.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.name
     *
     * @param name the value for user_base.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.id_card
     *
     * @return the value of user_base.id_card
     * @mbggenerated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.id_card
     *
     * @param idCard the value for user_base.id_card
     * @mbggenerated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.portrait_url
     *
     * @return the value of user_base.portrait_url
     * @mbggenerated
     */
    public String getPortraitUrl() {
        return portraitUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.portrait_url
     *
     * @param portraitUrl the value for user_base.portrait_url
     * @mbggenerated
     */
    public void setPortraitUrl(String portraitUrl) {
        this.portraitUrl = portraitUrl == null ? null : portraitUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.login_pwd_hash
     *
     * @return the value of user_base.login_pwd_hash
     * @mbggenerated
     */
    public String getLoginPwdHash() {
        return loginPwdHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.login_pwd_hash
     *
     * @param loginPwdHash the value for user_base.login_pwd_hash
     * @mbggenerated
     */
    public void setLoginPwdHash(String loginPwdHash) {
        this.loginPwdHash = loginPwdHash == null ? null : loginPwdHash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.is_migrated
     *
     * @return the value of user_base.is_migrated
     * @mbggenerated
     */
    public Boolean getIsMigrated() {
        return isMigrated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.is_migrated
     *
     * @param isMigrated the value for user_base.is_migrated
     * @mbggenerated
     */
    public void setIsMigrated(Boolean isMigrated) {
        this.isMigrated = isMigrated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.hash_mobile
     *
     * @return the value of user_base.hash_mobile
     *
     * @mbggenerated
     */
    public String getHashMobile() {
        return hashMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.hash_mobile
     *
     * @param hashMobile the value for user_base.hash_mobile
     *
     * @mbggenerated
     */
    public void setHashMobile(String hashMobile) {
        this.hashMobile = hashMobile == null ? null : hashMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.hash_id_card
     *
     * @return the value of user_base.hash_id_card
     *
     * @mbggenerated
     */
    public String getHashIdCard() {
        return hashIdCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.hash_id_card
     *
     * @param hashIdCard the value for user_base.hash_id_card
     *
     * @mbggenerated
     */
    public void setHashIdCard(String hashIdCard) {
        this.hashIdCard = hashIdCard == null ? null : hashIdCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_base.hash_name
     *
     * @return the value of user_base.hash_name
     *
     * @mbggenerated
     */
    public String getHashName() {
        return hashName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_base.hash_name
     *
     * @param hashName the value for user_base.hash_name
     *
     * @mbggenerated
     */
    public void setHashName(String hashName) {
        this.hashName = hashName == null ? null : hashName.trim();
    }

    /**
     * ???????
     * @return biz_type
     */
    public String getBizType() {
        return bizType;
    }

    /**
     * ???????
     *
     * @param bizType TODO
     */
    public void setBizType(String bizType) {
        this.bizType = bizType == null ? null : bizType.trim();
    }

    @Override
    public String toString() {
        return "UserBase{"
                + "id=" + this.id
                + ",gid=" + this.gid
                + ",createTime=" + this.createTime
                + ",updateTime=" + this.updateTime
                + ",nickname=" + this.nickname
                + ",mobile=" + this.mobile
                + ",name=" + this.name
                + ",bizType=" + this.bizType
                + ",idCard=" + this.idCard
                + ",portraitUrl=" + this.portraitUrl
                + ",loginPwdHash=" + this.loginPwdHash
                + ",isMigrated=" + this.isMigrated
                + ", hashMobile='" + hashMobile + '\''
                + ", hashIdCard='" + hashIdCard + '\''
                + ", hashName='" + hashName + '\''
                + "}";
    }
}