package org.tenio.interstellar.example.panda.model;

import java.util.ArrayList;
import java.util.List;

public class UserBaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbg.generated Mon Feb 07 15:22:04 CST 2022
     */
    private String limitClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbg.generated Mon Feb 07 15:22:04 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_base
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public UserBaseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Mon Feb 07 15:22:04 CST 2022
     */
    public void setLimitClause(String limitClause) {
        this.limitClause = limitClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Mon Feb 07 15:22:04 CST 2022
     */
    public String getLimitClause() {
        return this.limitClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbg.generated Mon Feb 07 15:22:04 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_base
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGidIsNull() {
            addCriterion("gid is null");
            return (Criteria) this;
        }

        public Criteria andGidIsNotNull() {
            addCriterion("gid is not null");
            return (Criteria) this;
        }

        public Criteria andGidEqualTo(String value) {
            addCriterion("gid =", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotEqualTo(String value) {
            addCriterion("gid <>", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThan(String value) {
            addCriterion("gid >", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidGreaterThanOrEqualTo(String value) {
            addCriterion("gid >=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThan(String value) {
            addCriterion("gid <", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLessThanOrEqualTo(String value) {
            addCriterion("gid <=", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidLike(String value) {
            addCriterion("gid like", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotLike(String value) {
            addCriterion("gid not like", value, "gid");
            return (Criteria) this;
        }

        public Criteria andGidIn(List<String> values) {
            addCriterion("gid in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotIn(List<String> values) {
            addCriterion("gid not in", values, "gid");
            return (Criteria) this;
        }

        public Criteria andGidBetween(String value1, String value2) {
            addCriterion("gid between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andGidNotBetween(String value1, String value2) {
            addCriterion("gid not between", value1, value2, "gid");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Integer value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Integer value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Integer value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Integer value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Integer> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Integer> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Integer value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Integer value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Integer value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Integer value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Integer> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Integer> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Integer value1, Integer value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNull() {
            addCriterion("nickname is null");
            return (Criteria) this;
        }

        public Criteria andNicknameIsNotNull() {
            addCriterion("nickname is not null");
            return (Criteria) this;
        }

        public Criteria andNicknameEqualTo(String value) {
            addCriterion("nickname =", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotEqualTo(String value) {
            addCriterion("nickname <>", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThan(String value) {
            addCriterion("nickname >", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameGreaterThanOrEqualTo(String value) {
            addCriterion("nickname >=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThan(String value) {
            addCriterion("nickname <", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLessThanOrEqualTo(String value) {
            addCriterion("nickname <=", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameLike(String value) {
            addCriterion("nickname like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotLike(String value) {
            addCriterion("nickname not like", value, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameIn(List<String> values) {
            addCriterion("nickname in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotIn(List<String> values) {
            addCriterion("nickname not in", values, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameBetween(String value1, String value2) {
            addCriterion("nickname between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andNicknameNotBetween(String value1, String value2) {
            addCriterion("nickname not between", value1, value2, "nickname");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("id_card in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlIsNull() {
            addCriterion("portrait_url is null");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlIsNotNull() {
            addCriterion("portrait_url is not null");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlEqualTo(String value) {
            addCriterion("portrait_url =", value, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlNotEqualTo(String value) {
            addCriterion("portrait_url <>", value, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlGreaterThan(String value) {
            addCriterion("portrait_url >", value, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlGreaterThanOrEqualTo(String value) {
            addCriterion("portrait_url >=", value, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlLessThan(String value) {
            addCriterion("portrait_url <", value, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlLessThanOrEqualTo(String value) {
            addCriterion("portrait_url <=", value, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlLike(String value) {
            addCriterion("portrait_url like", value, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlNotLike(String value) {
            addCriterion("portrait_url not like", value, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlIn(List<String> values) {
            addCriterion("portrait_url in", values, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlNotIn(List<String> values) {
            addCriterion("portrait_url not in", values, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlBetween(String value1, String value2) {
            addCriterion("portrait_url between", value1, value2, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andPortraitUrlNotBetween(String value1, String value2) {
            addCriterion("portrait_url not between", value1, value2, "portraitUrl");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashIsNull() {
            addCriterion("login_pwd_hash is null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashIsNotNull() {
            addCriterion("login_pwd_hash is not null");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashEqualTo(String value) {
            addCriterion("login_pwd_hash =", value, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashNotEqualTo(String value) {
            addCriterion("login_pwd_hash <>", value, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashGreaterThan(String value) {
            addCriterion("login_pwd_hash >", value, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashGreaterThanOrEqualTo(String value) {
            addCriterion("login_pwd_hash >=", value, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashLessThan(String value) {
            addCriterion("login_pwd_hash <", value, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashLessThanOrEqualTo(String value) {
            addCriterion("login_pwd_hash <=", value, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashLike(String value) {
            addCriterion("login_pwd_hash like", value, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashNotLike(String value) {
            addCriterion("login_pwd_hash not like", value, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashIn(List<String> values) {
            addCriterion("login_pwd_hash in", values, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashNotIn(List<String> values) {
            addCriterion("login_pwd_hash not in", values, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashBetween(String value1, String value2) {
            addCriterion("login_pwd_hash between", value1, value2, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andLoginPwdHashNotBetween(String value1, String value2) {
            addCriterion("login_pwd_hash not between", value1, value2, "loginPwdHash");
            return (Criteria) this;
        }

        public Criteria andIsMigratedIsNull() {
            addCriterion("is_migrated is null");
            return (Criteria) this;
        }

        public Criteria andIsMigratedIsNotNull() {
            addCriterion("is_migrated is not null");
            return (Criteria) this;
        }

        public Criteria andIsMigratedEqualTo(Boolean value) {
            addCriterion("is_migrated =", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedNotEqualTo(Boolean value) {
            addCriterion("is_migrated <>", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedGreaterThan(Boolean value) {
            addCriterion("is_migrated >", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_migrated >=", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedLessThan(Boolean value) {
            addCriterion("is_migrated <", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedLessThanOrEqualTo(Boolean value) {
            addCriterion("is_migrated <=", value, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedIn(List<Boolean> values) {
            addCriterion("is_migrated in", values, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedNotIn(List<Boolean> values) {
            addCriterion("is_migrated not in", values, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedBetween(Boolean value1, Boolean value2) {
            addCriterion("is_migrated between", value1, value2, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andIsMigratedNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_migrated not between", value1, value2, "isMigrated");
            return (Criteria) this;
        }

        public Criteria andHashMobileIsNull() {
            addCriterion("hash_mobile is null");
            return (Criteria) this;
        }

        public Criteria andHashMobileIsNotNull() {
            addCriterion("hash_mobile is not null");
            return (Criteria) this;
        }

        public Criteria andHashMobileEqualTo(String value) {
            addCriterion("hash_mobile =", value, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashMobileNotEqualTo(String value) {
            addCriterion("hash_mobile <>", value, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashMobileGreaterThan(String value) {
            addCriterion("hash_mobile >", value, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashMobileGreaterThanOrEqualTo(String value) {
            addCriterion("hash_mobile >=", value, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashMobileLessThan(String value) {
            addCriterion("hash_mobile <", value, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashMobileLessThanOrEqualTo(String value) {
            addCriterion("hash_mobile <=", value, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashMobileLike(String value) {
            addCriterion("hash_mobile like", value, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashMobileNotLike(String value) {
            addCriterion("hash_mobile not like", value, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashMobileIn(List<String> values) {
            addCriterion("hash_mobile in", values, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashMobileNotIn(List<String> values) {
            addCriterion("hash_mobile not in", values, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashMobileBetween(String value1, String value2) {
            addCriterion("hash_mobile between", value1, value2, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashMobileNotBetween(String value1, String value2) {
            addCriterion("hash_mobile not between", value1, value2, "hashMobile");
            return (Criteria) this;
        }

        public Criteria andHashIdCardIsNull() {
            addCriterion("hash_id_card is null");
            return (Criteria) this;
        }

        public Criteria andHashIdCardIsNotNull() {
            addCriterion("hash_id_card is not null");
            return (Criteria) this;
        }

        public Criteria andHashIdCardEqualTo(String value) {
            addCriterion("hash_id_card =", value, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashIdCardNotEqualTo(String value) {
            addCriterion("hash_id_card <>", value, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashIdCardGreaterThan(String value) {
            addCriterion("hash_id_card >", value, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("hash_id_card >=", value, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashIdCardLessThan(String value) {
            addCriterion("hash_id_card <", value, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashIdCardLessThanOrEqualTo(String value) {
            addCriterion("hash_id_card <=", value, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashIdCardLike(String value) {
            addCriterion("hash_id_card like", value, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashIdCardNotLike(String value) {
            addCriterion("hash_id_card not like", value, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashIdCardIn(List<String> values) {
            addCriterion("hash_id_card in", values, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashIdCardNotIn(List<String> values) {
            addCriterion("hash_id_card not in", values, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashIdCardBetween(String value1, String value2) {
            addCriterion("hash_id_card between", value1, value2, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashIdCardNotBetween(String value1, String value2) {
            addCriterion("hash_id_card not between", value1, value2, "hashIdCard");
            return (Criteria) this;
        }

        public Criteria andHashNameIsNull() {
            addCriterion("hash_name is null");
            return (Criteria) this;
        }

        public Criteria andHashNameIsNotNull() {
            addCriterion("hash_name is not null");
            return (Criteria) this;
        }

        public Criteria andHashNameEqualTo(String value) {
            addCriterion("hash_name =", value, "hashName");
            return (Criteria) this;
        }

        public Criteria andHashNameNotEqualTo(String value) {
            addCriterion("hash_name <>", value, "hashName");
            return (Criteria) this;
        }

        public Criteria andHashNameGreaterThan(String value) {
            addCriterion("hash_name >", value, "hashName");
            return (Criteria) this;
        }

        public Criteria andHashNameGreaterThanOrEqualTo(String value) {
            addCriterion("hash_name >=", value, "hashName");
            return (Criteria) this;
        }

        public Criteria andHashNameLessThan(String value) {
            addCriterion("hash_name <", value, "hashName");
            return (Criteria) this;
        }

        public Criteria andHashNameLessThanOrEqualTo(String value) {
            addCriterion("hash_name <=", value, "hashName");
            return (Criteria) this;
        }

        public Criteria andHashNameLike(String value) {
            addCriterion("hash_name like", value, "hashName");
            return (Criteria) this;
        }

        public Criteria andHashNameNotLike(String value) {
            addCriterion("hash_name not like", value, "hashName");
            return (Criteria) this;
        }

        public Criteria andHashNameIn(List<String> values) {
            addCriterion("hash_name in", values, "hashName");
            return (Criteria) this;
        }

        public Criteria andHashNameNotIn(List<String> values) {
            addCriterion("hash_name not in", values, "hashName");
            return (Criteria) this;
        }

        public Criteria andHashNameBetween(String value1, String value2) {
            addCriterion("hash_name between", value1, value2, "hashName");
            return (Criteria) this;
        }

        public Criteria andHashNameNotBetween(String value1, String value2) {
            addCriterion("hash_name not between", value1, value2, "hashName");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNull() {
            addCriterion("biz_type is null");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNotNull() {
            addCriterion("biz_type is not null");
            return (Criteria) this;
        }

        public Criteria andBizTypeEqualTo(String value) {
            addCriterion("biz_type =", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotEqualTo(String value) {
            addCriterion("biz_type <>", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThan(String value) {
            addCriterion("biz_type >", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThanOrEqualTo(String value) {
            addCriterion("biz_type >=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThan(String value) {
            addCriterion("biz_type <", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThanOrEqualTo(String value) {
            addCriterion("biz_type <=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLike(String value) {
            addCriterion("biz_type like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotLike(String value) {
            addCriterion("biz_type not like", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeIn(List<String> values) {
            addCriterion("biz_type in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotIn(List<String> values) {
            addCriterion("biz_type not in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeBetween(String value1, String value2) {
            addCriterion("biz_type between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotBetween(String value1, String value2) {
            addCriterion("biz_type not between", value1, value2, "bizType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_base
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_base
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }

    public void setLimitClause(int offset, int limit) {
        this.limitClause = offset + ", " + limit;
    }
}